2025-04-21 13:23:22.381186-03:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TORNEIO_REGISTERED_STARTUPS" not found; SQL statement:
SELECT s.*
FROM startup s
INNER JOIN torneio_registered_startups trs ON s.id = trs.registered_startups_id
WHERE trs.torneio_id = 4 [42102-232]
2025-04-21 13:23:34.107380-03:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TORNEIO_REGISTERED_STARTUPS" not found; SQL statement:
SELECT s.*
FROM startup s
INNER JOIN torneio_registered_startups trs ON s.id = trs.registered_startups_id
WHERE trs.torneio_id = 1 [42102-232]
2025-04-21 13:23:35.091091-03:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TORNEIO_REGISTERED_STARTUPS" not found; SQL statement:
SELECT s.*
FROM startup s
INNER JOIN torneio_registered_startups trs ON s.id = trs.registered_startups_id
WHERE trs.torneio_id = 1 [42102-232]
2025-04-21 17:20:35.717689-03:00 jdbc[14]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TORNEIOS" not found; SQL statement:
select * from torneios [42102-232]
2025-04-21 18:25:01.218098-03:00 jdbc[35]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
